app:
  repo: postgres
  grpc:
    port: 50051
  api:
    url: https://proverkacheka.com/api/v1/check/get
    token: 26822.2iEpvl7QCwvcwXGTI
db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: postgres